/**
 * This class is generated by jOOQ
 */
package models.jooq


import java.util.ArrayList
import java.util.Arrays
import java.util.List

import javax.annotation.Generated

import models.jooq.Sequences
import models.jooq.tables.Author

import org.jooq.Sequence
import org.jooq.Table
import org.jooq.impl.SchemaImpl


object Public {

	/**
	 * The reference instance of <code>public</code>
	 */
	val PUBLIC = new Public
}

/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = Array(
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	),
	comments = "This class is generated by jOOQ"
)
class Public extends SchemaImpl("public") {

	override def getSequences : List[Sequence[_]] = {
		val result = new ArrayList[Sequence[_]]
		result.addAll(getSequences0)
		result
	}

	private def getSequences0() : List[Sequence[_]] = {
		return Arrays.asList[Sequence[_]](
			Sequences.AUTHOR_ID_SEQ)
	}

	override def getTables : List[Table[_]] = {
		val result = new ArrayList[Table[_]]
		result.addAll(getTables0)
		result
	}

	private def getTables0() : List[Table[_]] = {
		return Arrays.asList[Table[_]](
			Author.AUTHOR)
	}
}
