/**
 * This class is generated by jOOQ
 */
package models.jooq


import javax.annotation.Generated

import models.jooq.tables.Author


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = Array(
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	),
	comments = "This class is generated by jOOQ"
)
object Tables {

	/**
	 * The table public.author
	 */
	val AUTHOR = models.jooq.tables.Author.AUTHOR
}
